export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';
export const USER_LOGIN_COMPLETED = 'USER_LOGIN_COMPLETED';

export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_LOGOUT_COMPLETED = 'USER_LOGOUT_COMPLETED';

export const DEVICE_MASTERLIST = 'DEVICE_MASTERLIST';
export const DEVICE_MASTERLIST_REQUEST = 'DEVICE_MASTERLIST_REQUEST';
export const DEVICE_MASTERLIST_ERROR = 'DEVICE_MASTERLIST_ERROR';
export const DEVICE_MASTERLIST_COMPLETED = 'DEVICE_MASTERLIST_COMPLETED';

export const SELECTED_ITEM = 'DEVICE_MASTERLIST';
export const SELECTED_ITEM_REQUEST = 'DEVICE_MASTERLIST_REQUEST';
export const SELECTED_ITEM_ERROR = 'DEVICE_MASTERLIST_ERROR';
export const SELECTED_ITEM_COMPLETED = 'DEVICE_MASTERLIST_COMPLETED';

export const STOCK = 'DEVICE_MASTERLIST';
export const STOCK_REQUEST = 'DEVICE_MASTERLIST_REQUEST';
export const STOCK_ERROR = 'DEVICE_MASTERLIST_ERROR';
export const STOCK_COMPLETED = 'DEVICE_MASTERLIST_COMPLETED';
