import DataTable, {COL_TYPES} from 'react-native-datatable-component';

export const tableData = [
  {
    id: 1,
    productCode: '480088168373',
    tag_name: 'HBR250G',
    description: 'Happy Booster Hotdog Regular 250g',
    badQty: 2,
    goodQty: 2,
    totalQty: 4,
    select: false,
  },
  {
    id: 2,
    productCode: '480021354834',
    tag_name: 'CNHDJ1KG',
    description: 'Champion Hotdog Jumbo 1 Kg',
    badQty: 2,
    goodQty: 2,
    totalQty: 4,
    select: false,
  },
  {
    id: 3,
    productCode: '125783542465',
    tag_name: 'BSCDK1K',
    description: 'Big Shot Cheesedoog King Size 1Kg',
    badQty: 2,
    goodQty: 2,
    totalQty: 4,
    select: false,
  },
  {
    id: 4,
    productCode: '235482354679',
    tag_name: 'WRFTLH250',
    description: 'Winner Foot Long Hotdog 250g',
    badQty: 2,
    goodQty: 2,
    totalQty: 4,
    select: false,
  },
  {
    id: 5,
    productCode: '480088168373',
    tag_name: 'HBR250G',
    description: 'Happy Booster Hotdog Regular 250g',
    badQty: 2,
    goodQty: 2,
    totalQty: 4,
    select: false,
  },
  {
    id: 6,
    productCode: '480021354834',
    tag_name: 'CNHDJ1KG',
    description: 'Champion Hotdog Jumbo 1 Kg',
    badQty: 2,
    goodQty: 2,
    totalQty: 4,
    select: false,
  },
  {
    id: 7,
    productCode: '125783542465',
    tag_name: 'BSCDK1K',
    description: 'Big Shot Cheesedoog King Size 1Kg',
    badQty: 2,
    goodQty: 2,
    totalQty: 4,
    select: false,
  },
  {
    id: 8,
    productCode: '235482354679',
    tag_name: 'WRFTLH250',
    description: 'Winner Foot Long Hotdog 250g',
    badQty: 2,
    goodQty: 2,
    totalQty: 4,
    select: false,
  },
];

export const columnNames = [
  'select',
  'productCode',
  'description',
  'badQty',
  'goodQty',
  'totalQty',
];

export const columnSettings = [
  {name: 'select', type: COL_TYPES.CHECK_BOX, width: '10%'},
  {name: 'productCode', type: COL_TYPES.STRING, width: '30%'},
  {name: 'description', type: COL_TYPES.STRING, width: '30%'},
  {name: 'badQty', type: COL_TYPES.INT, width: '10%'},
  {name: 'goodQty', type: COL_TYPES.INT, width: '10%'},
  {name: 'totalQty', type: COL_TYPES.INT, width: '10%'},
];
